ATTENDANCE=$((RANDOM%3))
FULL_TIME=2
PART_TIME=1
ABSENT=0
WAGE_PER_HOUR=20
FULL_TIME_WORKING_HOURS=8
PART_TIME_WORKING_HOURS=4
WORKING_DAYS_PER_MONTH=20
case ATTENDANCE in
	2)
		wage=$((ATTENDANCE*WAGE_PER_HOUR*FULL_TIME_WORKING_HOURS))
		echo "WORKING FULL DAY"
		echo "Salary per Month: " $(($WORKING_DAYS_PER_MONTH * $wage))
		;;
	1)
		wage=$((ATTENDANCE*WAGE_PER_HOUR*PART_TIME_WORKING_HOURS))
		echo "WORKING HALF DAY"
		echo "Salary per Month: " $(($WORKING_DAYS_PER_MONTH * $wage))
		;;
	*)
		echo "EMPLOYEE ABSENT"
		;;
esac